<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AudioCpp.CaptureTest</AssemblyName>
    <RootNamespace>AudioCpp.CaptureTest</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/AudioCpp.Audio/AudioCpp.Audio.csproj" />
  </ItemGroup>
</Project>
