#!/usr/bin/env python3
"""Import the audio.cpp web UI translations into the GUI's satellite resources.

The web UI keeps English in ``webui/native/src/lib/i18n.ts`` and one
``webui/native/lang/lang_<code>.json`` per language. Where this app uses the
same key for the same string, the translation is usable as-is.

That "same string" is the whole safety property. A borrowed key whose English
has drifted from upstream would silently take a translation of text we no
longer show, and nobody reading the resource file could tell. So this refuses
to write anything while any borrowed key's English differs, and names the keys.

Keys we do not share with upstream are left alone: they stay English until
someone who speaks the language supplies them. Nothing here invents a
translation.

Usage:
    tools/locales/import_webui_locales.py --audio-cpp ~/Programming/audio.cpp
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

GUI = Path(__file__).resolve().parents[2] / "src" / "AudioCpp.Bindings.Gui"
NEUTRAL = GUI / "Resources" / "Strings.resx"

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  {name} ({code}) — imported from the audio.cpp web UI.

  Generated by tools/locales/import_webui_locales.py. Do not hand-edit: the
  next import overwrites it, and an edit here is an untracked divergence from
  upstream's catalogue. Fix the wording upstream, or add the key to the neutral
  Strings.resx instead.

  Source: webui/native/lang/lang_{code}.json, audio.cpp, Apache-2.0,
  Copyright ShugoAI LLC. See NOTICE.

  Keys this app uses that upstream does not translate are absent, and fall back
  to the English in Strings.resx.
-->
<root>
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" msdata:Ordinal="1" />
              <xsd:attribute name="xml:space" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
"""


def read_english(audio_cpp: Path) -> dict[str, str]:
    """Pull the English catalogue out of the TypeScript it is declared in."""
    src = (audio_cpp / "webui/native/src/lib/i18n.ts").read_text(encoding="utf-8")
    start = src.index("const english: Record<string, string> = {")
    body = src[start : src.index("\n};", start)]
    pattern = r"^\s*'([^']+)':\s*('(?:[^'\\]|\\.)*'|\"(?:[^\"\\]|\\.)*\"),?\s*$"
    english: dict[str, str] = {}
    for match in re.finditer(pattern, body, re.M):
        raw = match.group(2)
        quote = raw[0]
        english[match.group(1)] = raw[1:-1].replace("\\" + quote, quote).replace("\\\\", "\\")
    return english


def read_ours() -> dict[str, str]:
    root = ET.parse(NEUTRAL).getroot()
    return {d.get("name"): (d.find("value").text or "") for d in root.findall("data")}


def escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--audio-cpp", type=Path, required=True, help="audio.cpp checkout")
    parser.add_argument("--check", action="store_true", help="verify only, write nothing")
    args = parser.parse_args()

    english = read_english(args.audio_cpp)
    ours = read_ours()
    borrowed = sorted(set(ours) & set(english))
    local_only = sorted(set(ours) - set(english))

    drifted = [k for k in borrowed if ours[k] != english[k]]
    if drifted:
        print("English has drifted from upstream for borrowed keys:", file=sys.stderr)
        for key in drifted:
            print(f"  {key}\n    ours:     {ours[key]!r}\n    upstream: {english[key]!r}", file=sys.stderr)
        print(
            "\nEither match upstream's wording, or rename the key so it is ours "
            "and stays English.",
            file=sys.stderr,
        )
        return 1

    print(f"{len(ours)} keys: {len(borrowed)} shared with upstream, {len(local_only)} ours alone")

    # A key nothing reads is a string a translator would work on for nothing.
    # Keys reached by name (nav.<page>, theme.<variant>) are spelled as a prefix
    # in the source, so match on that too.
    sources = "".join(
        path.read_text(encoding="utf-8")
        for path in GUI.rglob("*")
        if path.suffix in {".cs", ".axaml"} and "obj" not in path.parts and "bin" not in path.parts
    )
    dead = [
        key for key in ours
        if f"[{key}]" not in sources
        and f'"{key}"' not in sources
        and f'$"{key.rsplit(".", 1)[0]}.' not in sources
    ]
    if dead:
        print(f"  unreferenced: {', '.join(dead)}", file=sys.stderr)
        return 1

    written = []
    for lang_file in sorted((args.audio_cpp / "webui/native/lang").glob("lang_*.json")):
        data = json.loads(lang_file.read_text(encoding="utf-8"))
        code, name = data["code"], data["name"]
        translations = data["translations"]
        have = [k for k in borrowed if translations.get(k)]

        lines = [HEADER.format(name=name, code=code)]
        for key in have:
            lines.append(f'  <data name="{key}" xml:space="preserve">')
            lines.append(f"    <value>{escape(translations[key])}</value>")
            lines.append("  </data>")
        lines.append("</root>\n")

        target = GUI / "Resources" / f"Strings.{code}.resx"
        covered = 100 * len(have) / len(ours)
        print(f"  {code} ({name}): {len(have)}/{len(ours)} keys, {covered:.0f}% — {target.name}")
        if not args.check:
            target.write_text("\n".join(lines), encoding="utf-8")
        written.append(code)

    if args.check:
        print("check only; nothing written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
