#!/usr/bin/env python3
"""Regenerate the pseudo-locale from the neutral resource file.

Pseudo-localisation is a development aid, not a language: every string is
English with accented vowels and ⟦brackets⟧ around it. Accents prove the text
came through the resource lookup rather than a literal left in the XAML, and
the brackets make a clipped or truncated label obvious — a missing ⟧ is a
layout bug you can see without reading anything.

Run after changing Strings.resx:
    tools/locales/make_pseudo_locale.py
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path

RESOURCES = Path(__file__).resolve().parents[2] / "src" / "AudioCpp.Bindings.Gui" / "Resources"
ACCENTS = str.maketrans("aeiouyAEIOUY", "áéíóúýÁÉÍÓÚÝ")


def main() -> None:
    source = RESOURCES / "Strings.resx"
    text = source.read_text(encoding="utf-8")
    schema = text[text.index("<root>") : text.index("  <data")]

    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!--",
        "  Pseudo-locale. Generated by tools/locales/make_pseudo_locale.py; do not",
        "  hand-edit. Not a translation and not shipped in Release — see Loc.cs.",
        "-->",
        schema.rstrip("\n "),
    ]
    keys = ET.parse(source).getroot().findall("data")
    for data in keys:
        value = (data.find("value").text or "").translate(ACCENTS)
        escaped = value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        lines.append(f'  <data name="{data.get("name")}" xml:space="preserve">')
        lines.append(f"    <value>⟦{escaped}⟧</value>")
        lines.append("  </data>")
    lines.append("</root>\n")

    (RESOURCES / "Strings.qps-ploc.resx").write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(keys)} keys")


if __name__ == "__main__":
    main()
